#pragma once

#include <ArduinoJson.h>
#include <ESPWebPush.h>
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>

#include <string>
#include <vector>

#include "AlarmStore.h"

namespace BrewControl {

// Turns AlarmStore alerts into Web Push notifications, so the device can reach
// a phone with the dashboard closed.
//
// Why a hosted bootstrap page is in the picture: serviceWorker.register() and
// pushManager.subscribe() need a secure context, and this firmware serves
// plain http. A static page on GitHub Pages does the subscribing and hands the
// result back; from then on the device only talks outbound, which is a plain
// HTTPS client — the same thing FirmwareUpdater and MqttService already do.
//
// One VAPID keypair per installation, generated by that page and shared by
// every device: a browser holds exactly one subscription per service-worker
// scope, bound to one applicationServerKey, so per-device keys would need one
// static scope folder per device. See README.md.
//
// Persisted to NVS, deliberately not to /config/*.json: keeping the private
// key and the subscription endpoints out of GET /api/backup is the whole point
// — an endpoint URL is the only thing standing between a stranger and your
// notifications.
class PushService {
 public:
  PushService();

  // Loads NVS and, if a keypair and at least one subscription are stored,
  // brings the sender up. `hostname` is only kept for logging — the click-through
  // URL is rebuilt from the live IP on every push (see send()).
  void begin(const String& hostname);

  // Must be called every loop() iteration: applies a configuration change made
  // on the AsyncTCP task (re-init blocks, so it must not run there) and fires a
  // queued test notification.
  void tick();

  // Queues one alert for every stored subscription. Runs on loopTask, drained
  // from WebUI::tick alongside the SSE outbox. Silently does nothing when
  // unconfigured or before NTP sync — a VAPID JWT needs a real clock.
  void send(const AlarmStore::Alert& a);

  // GET /api/push. Never contains the private key.
  String serialize() const;

  // GET /api/push/keypair — the full pair, so the bootstrap page can keep its
  // copy current and hand it to the next device that has none. Gated behind
  // requireAuth() at the route, unlike every other read, and passed on through
  // the URL fragment so it never reaches the hosting server. Empty strings when
  // nothing is stored.
  String serializeKeypair() const;

  // POST /api/push/subscription — {publicKey, privateKey, endpoint, p256dh, auth}.
  // privateKey may be empty when publicKey is the one already stored: a browser
  // that subscribed against our key never holds the private half. An unknown
  // publicKey needs it, and drops every existing subscription — those were
  // taken out against the old key and would only ever answer 403. Re-posting a
  // known endpoint refreshes it in place.
  bool setSubscription(const JsonObject& j);

  bool removeSubscription(const char* id);

  // POST /api/push/test — queued here, sent from tick().
  void requestTest() { testPending_ = true; }

  // POST /api/push/reset — forget the keypair and every subscription.
  void reset();

 private:
  static constexpr size_t kMaxSubs = 4;  // NVS is 20 KB; mirrors AuthService's 4 session slots

  struct Sub {
    std::string endpoint;
    std::string p256dh;
    std::string auth;
    time_t      addedAt = 0;
  };

  void load_();
  void persist_() const;
  // deinit()/init() on the push worker — blocks, so loopTask only (tick()).
  void applyConfig_();
  void sendTo_(const Sub& s, const String& title, const String& body,
               const String& tag);
  // Alert → German notification text, mirroring the wording of the alert center.
  static void describe_(const AlarmStore::Alert& a, String& title, String& body);

  ESPWebPush push_;
  std::string vapidPub_;
  std::string vapidPriv_;
  std::vector<Sub> subs_;
  String hostname_;
  String lastError_;
  bool   initialized_   = false;
  volatile bool configDirty_ = false;
  volatile bool testPending_ = false;

  // Guards subs_/vapid*/lastError_: the REST handlers run on the AsyncTCP task,
  // send()/tick() on loopTask. Recursive to match the other stores.
  mutable SemaphoreHandle_t mutex_ = nullptr;
};

}  // namespace BrewControl
